### PR TITLE
Fix OS Release Comparing: 8.10

### LINKED ISSUE #43: Fix OS Release Comparing: 8.10
```
# Waiting on: https://github.com/mitre/redhat-enterprise-linux-8-stig-baseline/pull/39
SV-230221:
  justification: This should pass since 8.10 is in correct time, need to account for 8.10 and 8.1 - RHEL 8 must be a vendor-supported release.
  run: false
SV-250316:
  justification: This should not be running on 8.10 - RHEL 8 systems below version 8.2 must configure SELinux context type to allow the use of a non-default faillock tally directory.
  run: false
SV-230332:
  justification: This should not be running on 8.10 - RHEL 8 must automatically lock an account when three unsuccessful logon attempts occur.
  run: false
SV-230338:
  justification: This should not be running on 8.10 - RHEL 8 must ensure account lockouts persist.
  run: false
SV-230342:
  justification: This should not be running on 8.10 - RHEL 8 must log user name information when unsuccessful logon attempts occur.
  run: false
SV-230344:
  justification: This should not be running on 8.10 - RHEL 8 must include root when automatically locking an account until the locked account is released by an administrator when three unsuccessful logon attempts occur during a 15-minute time period.
  run: false
```

### PR DESCRIPTION
**Pull request by jrmetzger**
Tested against 8.10. Regex for 8.1 and fails test. Should add End of Line for regex to differ 8.1 with 8.10

### CODE REVIEW

**Review by aaronlippold — APPROVED** [review]

**Comment by aaronlippold** [comment]
Please update the patch version in the `inspec.yml` - as part of this PR as well

**Comment by aaronlippold** [comment]
each time we do a merge to main we have to update the version here so that inspec knows to pull down the updated code 

https://github.com/mitre/redhat-enterprise-linux-8-stig-baseline/blob/main/inspec.yml#L7C1-L7C16

**Comment by aaronlippold** [comment]
The logic here is:

```yaml
version: 1.14.1
```

STIG Version 1 Release 14 of the benchmark generally

and we have made .... 1,2,3 ... n patches and fixes to the test.

Then we can make a set of releases v1.14.x -> v1.14 -> v1 So folks can 'pin' as they need to and don't 'run off main' in real workflows.

<https://mitre.github.io/saf-training/courses/profile-dev-test/02.html>

**Comment by jrmetzger** [comment]
> The logic here is:
> 
> ```yaml
> version: 1.14.1
> ```
> 
> STIG Version 1 Release 14 of the benchmark generally
> 
> and we have made .... 1,2,3 ... n patches and fixes to the test.
> 
> Then we can make a set of releases v1.14.x -> v1.14 -> v1 So folks can 'pin' as they need to and don't 'run off main' in real workflows.
> 
> https://mitre.github.io/saf-training/courses/profile-dev-test/02.html

Will note for https://github.com/mitre/redhat-enterprise-linux-8-stig-baseline/tree/faillock_dir_dynamic branch upstream from this

File: controls/SV-230342.rb [hunk 1]
```diff
@@ -75,9 +75,9 @@
   tag cci: ['CCI-000044']
   tag nist: ['AC-7 a']
 
-  only_if('If the system is RHEL version 8.2 or newer, this check is not applicable.', impact: 0.0) {
-    (os.release.to_f) < 8.2
-  }
+  only_if('This check applies to RHEL versions 8.0 and 8.1. If the system is RHEL version 8.2 or newer, this check is Not Applicable.', impact: 0.0) do
+    Gem::Version.new(os.release) < Gem::Version.new('8.2')
```
Comment (jrmetzger) [inline controls/SV-230342.rb]:
```suggestion
    Gem::Version.new(os.release) <= Gem::Version.new('8.2')
```

File: controls/SV-230342.rb [hunk 2]
```diff
@@ -75,9 +75,9 @@
   tag cci: ['CCI-000044']
   tag nist: ['AC-7 a']
 
-  only_if('If the system is RHEL version 8.2 or newer, this check is not applicable.', impact: 0.0) {
-    (os.release.to_f) < 8.2
-  }
+  only_if('This check applies to RHEL versions 8.0 and 8.1. If the system is RHEL version 8.2 or newer, this check is Not Applicable.', impact: 0.0) do
```
Comment (jrmetzger) [inline controls/SV-230342.rb]:
```suggestion
  only_if('This check applies to RHEL versions 8.0, 8.1 and 8.2. If the system is RHEL version 8.3 or newer, this check is Not Applicable.', impact: 0.0) do
```

File: controls/SV-230332.rb [hunk 3]
```diff
@@ -87,7 +87,7 @@
     !input('central_account_management')
   }
 
-  if os.release.to_f >= 8.2
+  if Gem::Version.new(os.release) >= Gem::Version.new('8.2')
```
Comment (aaronlippold) [inline controls/SV-230332.rb]: We never call direct ruby in controls as it executes on the runner not the target. 

The `round() method off Float would likely be the better solution.

Something like `os.release.to_f.round(2)` may be what you are looking for. Chaining it this way off an inspec resource ensures the code runs on the target - in either local or remote scanning.

File: inspec.yml [hunk 4]
```diff
@@ -4,7 +4,7 @@ maintainer: MITRE SAF Team
 copyright: MITRE
 license: Apache-2.0
 summary: "This Security Technical Implementation Guide is published as a tool to improve the security of Department of Defense (DoD) information systems. The requirements are derived from the National Institute of Standards and Technology (NIST) 800-53 and related documents. Comments or proposed revisions to this document should be sent via email to the following address: disa.stig_spt@mail.mil."
-version: 1.14.1
+version: 1.14.2
```
Comment (aaronlippold) [inline inspec.yml:7]: My guidance to you on this was incorrect. I was reminded that we only update the version on release not on general updates to main. My appologies.

**Review by aaronlippold — CHANGES_REQUESTED** [review]

**Comment by aaronlippold** [comment]
I created a PR on the inspec side to fix this - https://github.com/inspec/inspec/pull/7271 

You may be able to just drop my udpated os resource into your profiles libraries directy to handle this as I took your approach and just moved it to the resource level vs the control level.

**Comment by aaronlippold** [comment]
Fixed by: https://github.com/inspec/inspec/pull/7279

**Comment by aaronlippold** [comment]
You will have to update the if statement to use the new `os.version` vs `os.release` once the PR merges. 

You can also steal the updated `platform.rb' and `os.rb` from the PR if you really want to.

**Comment by jrmetzger** [comment]
@aaronlippold what is the solution here?

**Comment by aaronlippold** [comment]
I updated the OS resource to do version correctly and updated all controls in the profile that were only for 8.1 or 8.2. 

I also put in a PR with inspec with it.

Let me know if this works for you.

**Comment by aaronlippold** [comment]
@jrmetzger NOTE: pulling the os resource into the RHEL9 profile and making a similar update will be necessary until my PR with inspec - https://github.com/inspec/inspec/pull/7294 is merged.

**Comment by jrmetzger** [comment]
Tested against 8.10 (modify /etc/os-release), working as expected

**Review by DMedina6 — APPROVED** [review]
Looks good
